declare enum GIF_VERSION {
    GIF87a = "GIF87a",
    GIF89a = "GIF89a"
}
declare enum EXTENSION_TYPE {
    graphics_control = 0,
    plain_text = 1,
    application = 2,
    comment = 3
}
declare const HEADER_BYTE_LENGTH = 6;
declare const LOGICAL_SCREEN_DESCRIPTOR_BYTE_LENGTH = 7;
declare const EXTENSION_FLAG = 33;
declare const GRAPHICS_CONTROL_EXTENSION_FLAG = 249;
declare const PLAIN_TEXT_EXTENSION_FLAG = 1;
declare const APPLICATION_EXTENSION_FLAG = 255;
declare const COMMENT_EXTENSION_FLAG = 254;
declare const IMAGE_DESCRIPTOR_FLAG = 44;
declare const IMAGE_DESCRIPTOR_BYTE_LENGTH = 10;
declare const IMAGE_DATA_END_FLAG = 0;
declare const PLAIN_TEXT_END_FLAG = 0;
declare const APPLICATION_END_FLAG = 0;
declare const APPLICATION_NETSCAPE = "NETSCAPE2.0";
declare const APPLICATION_XML_DATA = "XMP DataXMP";
declare const TRAILER_FLAG = 59;
declare const CLEAR_CODE = -1;
declare const END_OF_INFORMATION = -2;
export { GIF_VERSION, EXTENSION_TYPE, EXTENSION_FLAG, HEADER_BYTE_LENGTH, LOGICAL_SCREEN_DESCRIPTOR_BYTE_LENGTH, GRAPHICS_CONTROL_EXTENSION_FLAG, PLAIN_TEXT_EXTENSION_FLAG, APPLICATION_EXTENSION_FLAG, COMMENT_EXTENSION_FLAG, IMAGE_DESCRIPTOR_FLAG, IMAGE_DESCRIPTOR_BYTE_LENGTH, IMAGE_DATA_END_FLAG, PLAIN_TEXT_END_FLAG, APPLICATION_END_FLAG, APPLICATION_NETSCAPE, APPLICATION_XML_DATA, TRAILER_FLAG, CLEAR_CODE, END_OF_INFORMATION };
